# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ^14
      - run: npm install

      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - run: npm test
        if: runner.os != 'Linux'

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: test-release-please
      - run: npm run deploy
        env:
          VSCE_PAT: ${{secrets.VSCE_PAT}}
        if: ${{ steps.release.outputs.release_created }}
